// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

#pragma once

#include "frc/commands/Subsystem.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "frc/DigitalInput.h"
#include "frc/Encoder.h"
#include "frc/Servo.h"
#include "rev/CANSparkMax.h"

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

/**
 *
 *
 * @author ExampleAuthor
 */
class IonCanon: public frc::Subsystem {
private:
	// It's desirable that everything possible is private except
	// for methods that implement subsystem capabilities
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
std::shared_ptr<rev::CANSparkMax> shooterMotor1;
std::shared_ptr<rev::CANSparkMax> shooterMotor2;
std::shared_ptr<rev::CANSparkMax> turretMotor;
std::shared_ptr<frc::Servo> domeServo;
std::shared_ptr<frc::DigitalInput> turretReferenceSwitch;
std::shared_ptr<frc::Encoder> turretQuadEncoder;
std::shared_ptr<frc::DigitalInput> loadedSensor;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
public:
IonCanon();
	void InitDefaultCommand() override;
	void Periodic() override;
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS
	
	// Shooter 
	void LoadFuel();
	void EjectFuel();

	void Shoot();
	void SpinUpShooter();
	void SpinDownShooter();

	// Turn Turret
	void AimCam();
	void AimLeft();
	void AimRight();
	void AimUp();
	void AimDown();
	void AimStop();

};

