// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#pragma once

#include "frc/commands/Subsystem.h"
#include "../SPAMutil.h"

class LimeAide: public frc::Subsystem {
private:


	double m_targetsAvailable;
	double m_targetX;
	double m_targetY;
	double m_targetArea;
	double m_targetSkew;

    int m_nX = 3;
	float m_shooterSetPoints[3]={0., 0., 0.};
	float m_trgtAreas[3]={0., 1., 2.};
	float m_domeAngles[3]={0., 0., 0.};
	double m_limeSpeedSetpoint;
	double m_limeAngleSetpoint;

public:
	LimeAide();
	
	void InitDefaultCommand() override;
	void Periodic() override;

// LimeLight -- 
	void LimeRoxTrack();
	bool getLimeRoxInView();
	double getLimeRoxX();
	double getLimeRoxY();
	double getLimeRoxA();
	double getLimeRoxS();
	void setLimeRoxPipe0();
	void LimeRoxLEDOn();
	void LimeRoxLEDOff();
    void LimeRoxLEDBlnk();

	void LimeSpeeds(float xIn);
	void LimeAngles(float xIn);
    double getLimeSpdStPt();
	double getLimeDomeStPt();
	
};

