// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

#pragma once

#include "frc/commands/Subsystem.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "ctre/Phoenix.h"
#include "frc/DigitalInput.h"
#include "frc/Encoder.h"
#include "frc/Joystick.h"


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

/**
 *
 *
 * @author ExampleAuthor
 */
class TheForce: public frc::Subsystem {
private:
	// It's desirable that everything possible is private except
	// for methods that implement subsystem capabilities
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
std::shared_ptr<ctre::phoenix::motorcontrol::can::WPI_VictorSPX> liftMotor;
std::shared_ptr<ctre::phoenix::motorcontrol::can::WPI_VictorSPX> liftMotor1;
std::shared_ptr<frc::Encoder> liftEncoder;
std::shared_ptr<frc::DigitalInput> liftReferenceSwitch;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
public:
    static constexpr double BANGBANG_LO_SIDE = -50.;
    static constexpr double BANGBANG_HI_SIDE =  50.;
    static constexpr double WOOKIE_HEIGHT    =  1450.;
    static constexpr double EWOK_HEIGHT      =  50.;
    static constexpr double SOLO_HEIGHT      =  950.;
    double m_BangBang_Speed   =  0.50;
    double m_LiftSetPoint     =  0.;

    
	
    TheForce();
	void InitDefaultCommand() override;
	void Periodic() override;
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS
    void UseTheForce(std::shared_ptr<frc::Joystick> j);
    void YodaLift();
    void SetLiftWookie(); // max
    void SetLiftEwok();   // home
    void SetLiftSolo();   // hang
    void SetLiftHome();   // hang

};

