// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "Subsystems/Hyperdrive.h"
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "Commands/JoyDriveCommand.h"

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS


const double    kWheelWidth = 30.0;
const double    kWheelBase = 17.5;


Hyperdrive::Hyperdrive() : frc::Subsystem("Hyperdrive") {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
leftMotor1.reset(new rev::CANSparkMax(1, rev::CANSparkMax::MotorType::kBrushless));
//lw->AddActuator("Hyperdrive", "LeftMotor1", leftMotor1);

rightMotor1.reset(new rev::CANSparkMax(3, rev::CANSparkMax::MotorType::kBrushless));
//lw->AddActuator("Hyperdrive", "RightMotor1", rightMotor1);

differentialDrive.reset(new frc::DifferentialDrive(*leftMotor1, *rightMotor1));
AddChild("DifferentialDrive", differentialDrive);
differentialDrive->SetSafetyEnabled(true);
differentialDrive->SetExpiration(0.1);
differentialDrive->SetMaxOutput(1.0);

leftMotor2.reset(new rev::CANSparkMax(2, rev::CANSparkMax::MotorType::kBrushless));
//lw->AddActuator("Hyperdrive", "LeftMotor2", leftMotor2);

rightMotor2.reset(new rev::CANSparkMax(4, rev::CANSparkMax::MotorType::kBrushless));
//lw->AddActuator("Hyperdrive", "RightMotor2", rightMotor2);


rightMotor1->SetInverted(true);
rightMotor2->SetInverted(true);
leftMotor1->SetInverted(false);
leftMotor2->SetInverted(false);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    // Set the followers
    leftMotor2->Follow(*leftMotor1);
    rightMotor2->Follow(*rightMotor1);
}

void Hyperdrive::InitDefaultCommand() {
    // Set the default command for a subsystem here.
    // SetDefaultCommand(new MySpecialCommand());
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        SetDefaultCommand(new JoyDriveCommand());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
}

void Hyperdrive::Periodic() {
    // Put code here to be run every loop

}

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS


// Put methods for controlling this subsystem
// here. Call these from Commands.
void Hyperdrive::DriveArcade(std::shared_ptr<frc::Joystick> j)
{
    float x = j->GetX();            // raw 0
    float y = j->GetY();            // raw 1
    differentialDrive->ArcadeDrive(x, -y, true);
}

