// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "Subsystems/IonCanon.h"
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "Commands/AimCamera.h"

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

IonCanon::IonCanon() : frc::Subsystem("IonCanon") {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
shooterMotor.reset(new frc::NidecBrushless(2, 2));
AddChild("ShooterMotor", shooterMotor);

loaderSpitterMotor.reset(new frc::NidecBrushless(3, 3));
AddChild("LoaderSpitterMotor", loaderSpitterMotor);

domeServo.reset(new frc::Servo(4));
AddChild("DomeServo", domeServo);

turretMotor.reset(new frc::NidecBrushless(5, 4));
AddChild("TurretMotor", turretMotor);

turretReferenceSwitch.reset(new frc::DigitalInput(5));
AddChild("TurretReferenceSwitch", turretReferenceSwitch);

turretQuadEncoder.reset(new frc::Encoder(6, 7, false, frc::Encoder::k4X));
AddChild("TurretQuadEncoder", turretQuadEncoder);
turretQuadEncoder->SetDistancePerPulse(1.0);
turretQuadEncoder->SetPIDSourceType(frc::PIDSourceType::kRate);
loadedSensor.reset(new frc::DigitalInput(12));
AddChild("LoadedSensor", loadedSensor);


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
}

void IonCanon::InitDefaultCommand() {
    // Set the default command for a subsystem here.
    // SetDefaultCommand(new MySpecialCommand());
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        SetDefaultCommand(new AimCamera());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
}

void IonCanon::Periodic() {
    // Put code here to be run every loop

}

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS


// Put methods for controlling this subsystem
// here. Call these from Commands.

// Shooter 
void IonCanon::LoadFuel()
{
    
}

void IonCanon::EjectFuel()
{

}

void IonCanon::Shoot()
{

}

void IonCanon::SpinUpShooter()
{

}

void IonCanon::SpinDownShooter()
{

}

// Turn Turret
void IonCanon::AimCam()
{

}
void IonCanon::AimLeft()
{

}
void IonCanon::AimRight()
{

}
void IonCanon::AimUp()
{

}
void IonCanon::AimDown()
{

}
void IonCanon::AimStop()
{

}