// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "Subsystems/PlasmaTank.h"
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

PlasmaTank::PlasmaTank() : frc::Subsystem("PlasmaTank") {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
conveyorMotor.reset(new rev::CANSparkMax(9, rev::CANSparkMax::MotorType::kBrushless));
conveyorMotor1.reset(new rev::CANSparkMax(10, rev::CANSparkMax::MotorType::kBrushless));
//lw->AddActuator("PlasmaTank", "LoaderMotor", loaderMotor);

loaderMotor.reset(new ctre::phoenix::motorcontrol::can::WPI_TalonSRX(11));
//conveyorMotor.reset(new ctre::phoenix::motorcontrol::can::WPI_VictorSPX(10));



loadForce.reset(new frc::AnalogInput(0));
AddChild("LoadForce", loadForce);

  // Set the shooter motor follower
    conveyorMotor1->Follow(*conveyorMotor);


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
}

void PlasmaTank::InitDefaultCommand() {
    // Set the default command for a subsystem here.
    // SetDefaultCommand(new MySpecialCommand());
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
}

void PlasmaTank::Periodic() {
    // Put code here to be run every loop

}

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS


// Put methods for controlling this subsystem
// here. Call these from Commands.

