// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

#pragma once

#include "frc/TimedRobot.h"
#include "frc/commands/Command.h"
#include "frc/livewindow/LiveWindow.h"
#include "frc/smartdashboard/SendableChooser.h"
#include "SPAMutil.h"
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "Commands/AutonomousCommand.h"
#include "Subsystems/Hyperdrive.h"
#include "Subsystems/IonCannon.h"
#include "Subsystems/LifeSupport.h"
#include "Subsystems/PlasmaTank.h"
#include "Subsystems/TheForce.h"
#include "Subsystems/TractorBeam.h"
#include "Subsystems/WarpDriveInverter.h"
#include "Subsystems/LimeAide.h"


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "OI.h"

class Robot : public frc::TimedRobot {
public:
	frc::Command* autonomousCommand = nullptr;
	static std::unique_ptr<OI> oi;
	frc::LiveWindow *lw = frc::LiveWindow::GetInstance();
	frc::SendableChooser<frc::Command*> chooser;
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
static std::shared_ptr<Hyperdrive> hyperdrive;
static std::shared_ptr<LifeSupport> lifeSupport;
static std::shared_ptr<IonCannon> ionCannon;
static std::shared_ptr<PlasmaTank> plasmaTank;
static std::shared_ptr<TractorBeam> tractorBeam;
static std::shared_ptr<WarpDriveInverter> warpDriveInverter;
static std::shared_ptr<TheForce> theForce;
static std::shared_ptr<LimeAide> limeAide;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	void RobotInit() override;
	void DisabledInit() override;
	void DisabledPeriodic() override;
	void AutonomousInit() override;
	void AutonomousPeriodic() override;
	void TeleopInit() override;
	void TeleopPeriodic() override;
};
