// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

#pragma once

#include "frc/commands/Subsystem.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "frc/NidecBrushless.h"
#include "frc/RobotDrive.h"
#include "frc/Joystick.h"
#include <rev/CANSparkMAX.h>
#include "ctre/Phoenix.h"
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

/**
 *
 *
 * @author ExampleAuthor
 */
class BallShooter: public frc::Subsystem {
private:
	// It's desirable that everything possible is private except
	// for methods that implement subsystem capabilities
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	//std::shared_ptr<frc::NidecBrushless> ballShooter1;
	//std::shared_ptr<frc::NidecBrushless> ballshooter2;
	std::shared_ptr<rev::CANSparkMax> ballShooter1;
	std::shared_ptr<rev::CANSparkMax> ballShooter2;
	std::shared_ptr<frc::RobotDrive> shooterDrive;
	std::shared_ptr<can::WPI_VictorSPX> motor1_775;	
	std::shared_ptr<can::WPI_VictorSPX> motor2_775;	
	std::shared_ptr<frc::RobotDrive> drive775;
	
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
public:
BallShooter();
	void InitDefaultCommand() override;
	void Periodic() override;
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS
    void DriveShooter(std::shared_ptr<frc::Joystick> j);

};

